---
# tasks file for nginx
- name: update
  apt: update_cache=yes   
  
- name: Install Nginx
  apt: name=nginx state=latest


notify:
  - Start Nginx
  
- name: Enable ufw access for Nginx Full
  ufw:
    rule: allow
    name: "Nginx Full"

